spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarket?createDatabaseIfNotExists=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: fa0728b5-b0b5-4edb-aeac-09e958f82762
  expiration: 999999